name: Coverage

on:
  push:
    branches:
      - master
      - coverage
  pull_request:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, llvm-tools-preview
          toolchain: stable

      - name: Run tests
        env:
          CARGO_INCREMENTAL: "0"
          LLVM_PROFILE_FILE: "target/coverage/%p-%m.profraw"
          RUSTDOCFLAGS: "-Cinstrument-coverage"
          RUSTFLAGS: "-Cinstrument-coverage"
        run: cargo test issue

      - name: Install grcov
        run: cargo install grcov

      - name: debug
        run: |
          pwd
          ls -hAl

      - name: Generate coverage report
        run: >
          grcov target/coverage/ -s . --binary-path target/debug/ -t lcov --branch
          --ignore '../*' --ignore 'target/*' --ignore 'tests/*' --ignore-not-existing -o coverage.lcov
        #run: grcov . --binary-path target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore '../**' --ignore '/*' -o coverage.lcov


      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: coverage.lcov
          flags: rust
          token: ${{ secrets.CODECOV_TOKEN }}

