name: Coverage

on:
  push:
    branches:
      - master
      - coverage
  pull_request:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
          toolchain: stable

      - name: Install llvm-cov
        env:
          LLVM_COV_RELEASES: https://github.com/taiki-e/cargo-llvm-cov/releases
        run: |
          host=$(rustc -Vv | grep host | sed 's/host: //')
          curl -fsSL $LLVM_COV_RELEASES/latest/download/cargo-llvm-cov-$host.tar.gz | tar xzf - -C "$HOME/.cargo/bin"

      - name: Generate coverage report
        run: cargo llvm-cov --lcov --output-path coverage.lcov -- input_sorting

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: coverage.lcov
          flags: rust
          token: ${{ secrets.CODECOV_TOKEN }}

